---
- name: Enable hyperland copr
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: kasion/Hyprland-git

- name: Install hyprland packages
  ansible.builtin.package:
    name:
      - hyprland
    state: latest

- name: Copy hyprland config
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/hypr"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/"
    force: true
