---
- name: Install neovim packages
  ansible.builtin.package:
    name:
      - neovim
      - python3-neovim
      - rsync
    state: latest
  become: true

- name: Create nvim config directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
    state: directory
    mode: '0755'

- name: Copy neovim config
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/nvim-0.5/"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim/"
