---
- name: Install waybar packages
  ansible.builtin.package:
    name:
      - waybar
    state: latest
  become: true

- name: Copy waybar config
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/waybar"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/"
    force: true
