---
- name: Install zsh packages
  ansible.builtin.package:
    name:
      - zsh
      - zsh-lovers
    state: latest
  become: true

- name: Copy zshrc to home dir
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/zsh/zshrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    force: true

- name: Switch shell
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh 
  become: true

- name: Install sheldon config
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/sheldon/plugins.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/sheldon/"
    force: true

- name: Install starship config
  ansible.builtin.copy:
    src: "{{ local_git_path }}/config/starship.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/"
